<template>
  <div class="workspace-page">
    <section class="page-intro"><div><p>全局数据治理</p><h2>健康档案监管</h2><span>系统管理员通过专属接口处理全局档案，不进入普通用户的“我的档案”。</span></div><el-button type="primary" @click="openCreate">新建监管档案</el-button></section>
    <el-alert v-if="errorMessage" :title="errorMessage" type="error" show-icon :closable="false" />
    <el-card shadow="never" class="filter-card">
      <div class="filter-row filter-row--wrap"><label class="filter-field"><span class="filter-field-label">档案归属人</span><el-input v-model="filters.owner_keyword" clearable placeholder="输入用户名" @keyup.enter="search" /></label><label class="filter-field"><span class="filter-field-label">体检机构</span><el-select v-model="filters.institution_id" clearable placeholder="全部机构"><el-option v-for="item in institutions" :key="item.id" :label="`${item.name} · ${item.branch_name}`" :value="item.id" /></el-select></label><label class="filter-field filter-field--compact"><span class="filter-field-label">档案状态</span><el-select v-model="filters.status" clearable placeholder="全部状态"><el-option label="草稿" value="draft" /><el-option label="待确认" value="parsed" /><el-option label="已确认" value="confirmed" /></el-select></label><div class="filter-actions"><el-button type="primary" @click="search">查询</el-button><el-button @click="resetFilters">重置</el-button></div></div>
    </el-card>
    <el-card shadow="never" class="table-card">
      <el-table :data="items" v-loading="loading" empty-text="暂无档案">
        <el-table-column label="档案 ID" width="120"><template #default="scope">{{ formatRecordDisplayId(scope.row) }}</template></el-table-column><el-table-column prop="exam_date" label="体检日期" width="120" /><el-table-column label="归属人" min-width="120"><template #default="scope">{{ scope.row.owner?.username || `用户 ${scope.row.owner_id}` }}</template></el-table-column><el-table-column label="机构" min-width="200"><template #default="scope">{{ scope.row.institution ? `${scope.row.institution.name} · ${scope.row.institution.branch_name}` : "未关联机构" }}</template></el-table-column><el-table-column label="套餐" min-width="150"><template #default="scope">{{ scope.row.package?.name || "未选择套餐" }}</template></el-table-column><el-table-column prop="indicator_count" label="指标" width="80" /><el-table-column label="状态" width="100"><template #default="scope"><el-tag :type="statusTag(scope.row.status)">{{ statusText(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="200" fixed="right"><template #default="scope"><el-button link type="primary" @click="openDetail(scope.row.id)">详情</el-button><el-button link @click="openEdit(scope.row)">编辑</el-button><el-button link type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column>
      </el-table>
      <div class="pagination-row" v-if="pagination.total>pagination.page_size"><el-pagination background layout="prev, pager, next, total" :current-page="pagination.page" :page-size="pagination.page_size" :total="pagination.total" @current-change="changePage" /></div>
    </el-card>

    <el-dialog v-model="recordDialogVisible" :title="recordForm.id ? '编辑监管档案' : '新建监管档案'" width="620px" :close-on-click-modal="false">
      <el-form :model="recordForm" label-position="top">
        <div class="responsive-form-grid"><el-form-item label="档案归属人" required><el-select v-model="recordForm.owner_id" filterable style="width:100%"><el-option v-for="user in users" :key="user.id" :label="`${user.username}（${roleLabel(user.role)}）`" :value="user.id" /></el-select></el-form-item><el-form-item label="体检日期" required><el-date-picker v-model="recordForm.exam_date" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item><el-form-item label="档案状态" required><el-select v-model="recordForm.status" style="width:100%"><el-option label="草稿" value="draft" /><el-option label="待确认" value="parsed" /><el-option label="已确认" value="confirmed" /></el-select></el-form-item><el-form-item label="体检机构（可选）"><el-select v-model="recordForm.institution_id" clearable placeholder="暂不选取" style="width:100%" @change="onRecordInstitutionChange"><el-option v-for="item in institutions" :key="item.id" :label="`${item.name} · ${item.branch_name}`" :value="item.id" /></el-select></el-form-item><el-form-item label="体检套餐（可选）" class="form-grid-full"><el-select v-model="recordForm.package_id" clearable :disabled="!recordForm.institution_id" placeholder="暂不选取" style="width:100%"><el-option v-for="item in currentPackages" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item></div>
        <el-alert v-if="recordForm.institution_id" title="档案确认后，标准化数据会自动向对应机构管理员只读开放。" type="warning" show-icon :closable="false" />
      </el-form>
      <template #footer><el-button @click="recordDialogVisible=false">取消</el-button><el-button type="primary" :loading="recordSaving" @click="saveRecord">保存</el-button></template>
    </el-dialog>

    <el-drawer v-model="detailVisible" title="全局档案详情" size="min(780px, 95vw)">
      <el-skeleton v-if="detailLoading" :rows="8" animated />
      <template v-else-if="detail">
        <el-descriptions :column="2" border class="detail-descriptions"><el-descriptions-item label="档案 ID">{{ formatRecordDisplayId(detail) }}</el-descriptions-item><el-descriptions-item label="归属人">{{ detail.owner?.username }}</el-descriptions-item><el-descriptions-item label="体检日期">{{ detail.exam_date }}</el-descriptions-item><el-descriptions-item label="状态">{{ statusText(detail.status) }}</el-descriptions-item><el-descriptions-item label="机构">{{ detail.institution?.name || "未关联" }}</el-descriptions-item><el-descriptions-item label="套餐">{{ detail.package?.name || "未选择" }}</el-descriptions-item></el-descriptions>
        <div class="drawer-toolbar"><div><h3>健康指标</h3><p>数值会由后端统一规范并重新判断异常。</p></div><el-button type="primary" @click="openIndicatorCreate">新增指标</el-button></div>
        <el-table :data="detail.indicators || []" empty-text="暂无指标"><el-table-column label="指标" min-width="190"><template #default="scope">{{ scope.row.indicator?.code }} · {{ scope.row.indicator?.name }}</template></el-table-column><el-table-column prop="value" label="结果" min-width="100" /><el-table-column label="异常" width="90"><template #default="scope"><el-tag :type="scope.row.is_abnormal?'danger':'success'">{{ scope.row.is_abnormal?"异常":"正常" }}</el-tag></template></el-table-column><el-table-column label="操作" width="130"><template #default="scope"><el-button link type="primary" @click="openIndicatorEdit(scope.row)">编辑</el-button><el-button link type="danger" @click="removeIndicator(scope.row)">删除</el-button></template></el-table-column></el-table>
      </template>
    </el-drawer>

    <el-dialog v-model="indicatorDialogVisible" :title="indicatorForm.id ? '编辑指标' : '新增指标'" width="520px" append-to-body>
      <el-form :model="indicatorForm" label-position="top"><el-form-item label="标准指标" required><el-select v-model="indicatorForm.indicator_dict_id" filterable style="width:100%"><el-option v-for="item in indicatorDicts" :key="item.id" :label="`${item.code} - ${item.name}${item.unit ? `（${item.unit}）` : ''}`" :value="item.id" /></el-select></el-form-item><el-form-item label="指标结果" required><el-input v-model="indicatorForm.value" placeholder="可输入带单位的原始结果，后端会规范化" /></el-form-item></el-form>
      <template #footer><el-button @click="indicatorDialogVisible=false">取消</el-button><el-button type="primary" :loading="indicatorSaving" @click="saveIndicator">保存</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { addAdminRecordIndicator, createAdminRecord, deleteAdminRecord, deleteAdminRecordIndicator, fetchAdminInstitutions, fetchAdminPackages, fetchAdminRecord, fetchAdminRecords, updateAdminRecord, updateAdminRecordIndicator } from "../../api/admin";
import { fetchIndicatorDicts } from "../../api/indicators";
import { fetchUsers } from "../../api/users";
import { formatRecordDisplayId } from "../../utils/recordDisplayId";
import { roleLabel } from "../../utils/roles";

const items=ref([]),institutions=ref([]),users=ref([]),indicatorDicts=ref([]),loading=ref(false),errorMessage=ref("");const filters=reactive({owner_keyword:"",institution_id:null,status:""});const pagination=reactive({page:1,page_size:20,total:0,pages:0});
const packageMap=ref({});const recordDialogVisible=ref(false),recordSaving=ref(false);const recordForm=reactive({id:null,owner_id:null,exam_date:"",status:"confirmed",institution_id:null,package_id:null});const currentPackages=computed(()=>recordForm.institution_id?packageMap.value[recordForm.institution_id]||[]:[]);
const detailVisible=ref(false),detailLoading=ref(false),detail=ref(null);const indicatorDialogVisible=ref(false),indicatorSaving=ref(false),indicatorForm=reactive({id:null,indicator_dict_id:null,value:""});
const statusText=(status)=>({draft:"草稿",parsed:"待确认",confirmed:"已确认"}[status]||status);const statusTag=(status)=>({draft:"info",parsed:"warning",confirmed:"success"}[status]||"");
async function loadBase(){const[instRes,userRes,dictRes]=await Promise.all([fetchAdminInstitutions(),fetchUsers(),fetchIndicatorDicts()]);institutions.value=instRes.data.items||[];users.value=userRes.data.items||[];indicatorDicts.value=dictRes.data.items||[];}
async function load(){loading.value=true;errorMessage.value="";try{const{data}=await fetchAdminRecords({page:pagination.page,page_size:pagination.page_size,owner_keyword:filters.owner_keyword.trim()||undefined,institution_id:filters.institution_id||undefined,status:filters.status||undefined});items.value=data.items||[];Object.assign(pagination,data.pagination||{total:items.value.length});}catch(error){errorMessage.value=error?.response?.data?.message||"全局档案加载失败";}finally{loading.value=false;}}
function search(){pagination.page=1;load();}function resetFilters(){Object.assign(filters,{owner_keyword:"",institution_id:null,status:""});search();}function changePage(page){pagination.page=page;load();}
async function loadPackages(id){if(!id||packageMap.value[id])return;const{data}=await fetchAdminPackages(id);packageMap.value={...packageMap.value,[id]:data.items||[]};}
async function onRecordInstitutionChange(id){recordForm.package_id=null;if(id)try{await loadPackages(id);}catch(error){ElMessage.error(error?.response?.data?.message||"套餐加载失败");}}
function resetRecord(){Object.assign(recordForm,{id:null,owner_id:users.value[0]?.id||null,exam_date:"",status:"confirmed",institution_id:null,package_id:null});}
function openCreate(){resetRecord();recordDialogVisible.value=true;}
async function openEdit(item){Object.assign(recordForm,{id:item.id,owner_id:item.owner_id,exam_date:item.exam_date,status:item.status,institution_id:item.institution_id,package_id:item.package_id});if(item.institution_id)await loadPackages(item.institution_id);recordDialogVisible.value=true;}
async function saveRecord(){if(!recordForm.owner_id||!recordForm.exam_date){ElMessage.error("请选择归属人与体检日期");return;}recordSaving.value=true;const payload={owner_id:recordForm.owner_id,exam_date:recordForm.exam_date,status:recordForm.status,institution_id:recordForm.institution_id||null,package_id:recordForm.package_id||null};try{if(recordForm.id)await updateAdminRecord(recordForm.id,payload);else await createAdminRecord(payload);ElMessage.success("档案已保存");recordDialogVisible.value=false;await load();}catch(error){ElMessage.error(error?.response?.data?.message||"档案保存失败");}finally{recordSaving.value=false;}}
async function remove(item){try{await ElMessageBox.confirm(`确认删除档案 ${formatRecordDisplayId(item)}？该操作无法恢复。`,`删除档案`,{type:"warning",confirmButtonText:"确认删除",cancelButtonText:"取消"});await deleteAdminRecord(item.id);ElMessage.success("档案已删除");await load();}catch(error){if(error!=="cancel"&&error!=="close")ElMessage.error(error?.response?.data?.message||"删除失败");}}
async function openDetail(id){detailVisible.value=true;detailLoading.value=true;detail.value=null;try{const{data}=await fetchAdminRecord(id);detail.value=data.item;}catch(error){detailVisible.value=false;ElMessage.error(error?.response?.data?.message||"详情加载失败");}finally{detailLoading.value=false;}}
function openIndicatorCreate(){Object.assign(indicatorForm,{id:null,indicator_dict_id:null,value:""});indicatorDialogVisible.value=true;}function openIndicatorEdit(item){Object.assign(indicatorForm,{id:item.id,indicator_dict_id:item.indicator_dict_id,value:item.value||""});indicatorDialogVisible.value=true;}
async function saveIndicator(){if(!indicatorForm.indicator_dict_id||!indicatorForm.value.trim()){ElMessage.error("请选择指标并填写结果");return;}indicatorSaving.value=true;const payload={indicator_dict_id:indicatorForm.indicator_dict_id,value:indicatorForm.value.trim()};try{if(indicatorForm.id)await updateAdminRecordIndicator(detail.value.id,indicatorForm.id,payload);else await addAdminRecordIndicator(detail.value.id,payload);ElMessage.success("指标已保存");indicatorDialogVisible.value=false;await openDetail(detail.value.id);await load();}catch(error){ElMessage.error(error?.response?.data?.message||"指标保存失败");}finally{indicatorSaving.value=false;}}
async function removeIndicator(item){try{await ElMessageBox.confirm("确认删除该指标？","删除指标",{type:"warning",confirmButtonText:"删除",cancelButtonText:"取消"});await deleteAdminRecordIndicator(detail.value.id,item.id);ElMessage.success("指标已删除");await openDetail(detail.value.id);await load();}catch(error){if(error!=="cancel"&&error!=="close")ElMessage.error(error?.response?.data?.message||"删除失败");}}
onMounted(async()=>{try{await Promise.all([loadBase(),load()]);}catch(error){errorMessage.value=error?.response?.data?.message||"页面初始化失败";}});
</script>
